### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Snifexx** [Yona168/MultiblockAPI#5]
Whenever i try to build my plugin this error shows up:

`C:\Users\matte\Documents\Intellij Projects\Spigot\VanillaPlus\src\main\java\me\snifex\survivalplus\logic\smeltery\SmelteryLogic.java:49:22
java: cannot access com.gitlab.avelyn.architecture.base.Parent
  class file for com.gitlab.avelyn.architecture.base.Parent not found`

Line 49 is just the MultiblockAPI access

`API api = MultiblockAPI.getAPI();`

Any help?

**Comment by ygins** [comment]
Hi! I'm sorry, I was unavailable for a while, and just saw this issue. Unfortunately, the plugin is no longer undergoing active development.

**Comment by ygins** [comment]
Thank you for raising this issue. I resolved the issue in v1.0.1, see the updated README.
